name: Build and Push Docker image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Make script executable
      run: chmod +x ci-cd.py
    - name: Run ci-cd.py
      run: ./ci-cd.py
